name: test
on:
  pull_request:
    branches: [ develop ]
    
    
jobs:
  vapor_macos:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4_beta.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - name: Install xcbeautify
      uses: Cyberbeni/install-swift-tool@v2
      with:
        url: https://github.com/Cyberbeni/xcbeautify
        branch: linux-fixes # optional
    - name: build
      run: swift build -v
    - name: Test
      run: |
        set -o pipefail
        swift test --enable-test-discovery --sanitize=thread --enable-code-coverage | xcbeautify
    - name: Codecov
      run: |
        llvm-cov export -format="lcov" .build/debug/TypedNotificationCenterPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
        bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter' -n 'linux' -F 'linux'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  vapor_xenial:
    container:
      image: vapor/swift:5.2-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
  vapor_bionic:
    container:
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
