name: Swift-Linux

on:
  pull_request:
    branches: [ develop ]

jobs:
  test-linux:
    runs-on: ubuntu20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Swift requied dep util for ubuntu20.04
      run: apt-get install binutils git gnupg2 libc6-dev libcurl4 libedit2 libgcc-9-dev libpython2.7 libsqlite3-0 libstdc++-9-dev libxml2 libz3-dev pkg-config tzdata zlib1g-dev
    - name: Display
      run: swift --version
    - name: Install xcbeautify
      uses: Cyberbeni/install-swift-tool@v1
      with:
        url: https://github.com/Cyberbeni/xcbeautify
        branch: linux-fixes
    - name: build
      run: swift build -v
    - name: Test
      run: |
        set -o pipefail
        swift test --enable-code-coverage | xcbeautify
    - name: Codecov
      run: |
        llvm-cov export -format="lcov" .build/debug/TypedNotificationCenterPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
        bash <(curl -s https://codecov.io/bash) -J 'TypedNotificationCenter' -n 'linux' -F 'linux'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
