name: Swift

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Swift on Linux
      uses: sersoft-gmbh/SwiftyActions@v1.0.2
      with:
        # The (released) Swift version (e.g. 5.2.1) to install. If given, `branch-name` and `version-tag` are ignored.
        release-version: 5.2
        # The branch of the Swift version to install (e.g. swift-5.2.1-release). Required if `release-version` is not set!
        platform: ubuntu20.04# optional, default is ubuntu18.04
        # Whether or not the installation of dependencies (via apt) should be skipped.
        skip-apt: # optional
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
